
name: Deploy to Digital Ocean

on:
  push:
    branches: [ "master" ]

# permissions:
#   contents: read

jobs:
  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    # needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Add the private SSH key to the ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"
      - name: Build and deploy images on DigitalOcean
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          scp -P 4402  -o StrictHostKeyChecking=no -r ci_cd/ shah@shahtech.org:/
          ssh -p 4402 -o StrictHostKeyChecking=no shah@shahtech.org << 'ENDSSH'
            cd /ci_cd
            pip3 install -r requirements.txt
            python3 shah.py
          ENDSSH



    
